In [8]:
import numpy as np
print("✅ Ядро работает! NumPy импортирован!")
print("Версия Python:", np.__version__)

✅ Ядро работает! NumPy импортирован!
Версия Python: 2.3.4


In [ ]:
list = [1, 2, 3, 4, 5]
np_array = np.array(list) #Преобразуем в numpy массив
np_array

array([1, 2, 3, 4, 5])

In [ ]:
#Создадим одномерный массив с нулями, двумерный массив, 
#Имеющий 5 строк и 5 столбцов и одномерный массив с диапозоном от 0 до 9
zeros_array = np.zeros(5)
ones_array = np.ones((5,5))
range_array = np.arange(10)
zeros_array, ones_array, range_array

(array([0., 0., 0., 0., 0.]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Посмотрим форму (размерность) и тип данных массива ones_array
print("Shape:", ones_array.shape) 
print("Data type:", ones_array.dtype)


Shape: (5, 5)
Data type: float64


In [21]:
# Возьмём третий элемент массива range_array
third_element = range_array[2]

# Возьмём срез: элементы с индексами 2,3,4
slice_part = range_array[2:5]

third_element, slice_part


(np.int64(2), array([2, 3, 4]))

In [14]:
# Создадим два массива
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Поэлементное сложение
sum_result = a + b

# Поэлементное умножение
mul_result = a * b

sum_result, mul_result


(array([5, 7, 9]), array([ 4, 10, 18]))

In [15]:
# Среднее значение элементов массива b
mean_value = b.mean()

# Максимум и минимум
max_value = b.max()
min_value = b.min()

mean_value, max_value, min_value


(np.float64(5.0), np.int64(6), np.int64(4))